select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount)
from customer
group by(gender)

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id
from customer
where purchase_amount > (
select avg(purchase_amount)
from customer
)

--Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, avg(review_rating) as avg_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,avg(purchase_amount) as avg_pur_amt 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue

select subscription_status ,avg(purchase_amount) as avg_pur_amt, sum(purchase_amount) as total_amt
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased as item,
count (
	case
	when discount_applied = 'Yes' then 1 
	end
		)*100/count(*) as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total
-- CTE common table expression structure

with customer_type as (
    select customer_id,
           case
               when previous_purchases in (0,1) then 'New'
               when previous_purchases between 2 and 10 then 'Returning'
               else 'Loyal'
           end as customer_segment
    from customer
)

select customer_segment,
       count(*) as "No.of customers"
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

with product_count as (
    select category,
           item_purchased,
           count(*) as total_purchases
    from customer
    group by category, item_purchased
),

ranked_products as (
    select category,
           item_purchased,
           total_purchases,
           row_number() over (
               partition by category
               order by total_purchases desc
           ) as ranking
    from product_count
)

select category,
       item_purchased,
       total_purchases
from ranked_products
where ranking <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status; 


--Q10. What is the revenue contribution of each age group? SELECT

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;